name: 'Go cover diff'
description: ''
branding:
  icon: 'eye'
  color: 'blue'
inputs:
  base:
    description: "Base branch for comparison."
    required: false
    default: "main"
  # TODO add a change threshold to fail the PR if we go below threshold
runs:
  using: 'composite'
  steps:
    - uses: ./.github/actions/coverdiff.yaml
